name: ViperSample
options:
  bundleIdPrefix: com.hicka04
  deploymentTarget:
    iOS: 11.0
targets:
  ViperSample:
    type: application
    platform: iOS
    sources:
      - ViperSample
    settings:
      base:
        DEVELOPMENT_TEAM: 8RYHZQ93KG
        INFOPLIST_FILE: ViperSample/Application/Info.plist
    dependencies:
      - target: ViperSampleDomain
  ViperSampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ViperSampleTests
    settings:
      base:
        DEVELOPMENT_TEAM: 8RYHZQ93KG
        INFOPLIST_FILE: ViperSampleTests/Info.plist
    dependencies:
      - target: ViperSample
      - package: Quick
      - package: Nimble
  ViperSampleDomain:
    type: framework
    platform: iOS
    sources:
      - ViperSampleDomain
    settings:
      base:
        DEVELOPMENT_TEAM: 8RYHZQ93KG
        INFOPLIST_FILE: ViperSampleDomain/Info.plist
    dependencies:
      - target: ViperSampleData
  ViperSampleDomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ViperSampleDomainTests
    settings:
      base:
        DEVELOPMENT_TEAM: 8RYHZQ93KG
        INFOPLIST_FILE: ViperSampleDomainTests/Info.plist
    dependencies:
      - target: ViperSampleDomain
      - package: Quick
      - package: Nimble
  ViperSampleData:
    type: framework
    platform: iOS
    sources:
      - ViperSampleData
    settings:
      base:
        DEVELOPMENT_TEAM: 8RYHZQ93KG
        INFOPLIST_FILE: ViperSampleDomain/Info.plist
  ViperSampleDataTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ViperSampleDataTests
    settings:
      base:
        DEVELOPMENT_TEAM: 8RYHZQ93KG
        INFOPLIST_FILE: ViperSampleDomainTests/Info.plist
    dependencies:
      - target: ViperSampleData
      - package: Quick
      - package: Nimble
packages:
  Quick:
    url: https://github.com/Quick/Quick.git
    majorVersion: 2.2.0
  Nimble:
    url: https://github.com/Quick/Nimble.git
    version: 8.0.2
schemes:
  ViperSample:
    build:
      targets:
        ViperSample: all
        ViperSampleTests: test
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - ViperSample
      targets:
        - name: ViperSampleTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  ViperSampleDomain:
    build:
      targets:
        ViperSampleDomain: all
        ViperSampleDomainTests: test
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - ViperSampleDomain
      targets:
        - name: ViperSampleDomainTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  ViperSampleData:
    build:
      targets:
        ViperSampleData: all
        ViperSampleDataTests: test
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - ViperSampleData
      targets:
        - name: ViperSampleDataTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release